### PR TITLE
Modified to match latest Swift 3 syntax

### PR DESCRIPTION
**Pull request by Minitour**
I modified the following (These were causing compilation issues):

in line 698:
Before:
```swift
for key in Array(parameters.keys).sorted(isOrderedBefore: <) {
            let value: AnyObject! = parameters[key]
            components += self.queryComponents(key, value)
}
```
After:
```swift
for key in Array(parameters.keys).sorted(by: <){
            let value: AnyObject! = parameters[key]
            components += self.queryComponents(key, value)
}
```

in line 739:
Before:
```swift
if let component = URL.lastPathComponent {
                    partFilename = component
}
```

After:
```swift
if let component:String = URL.lastPathComponent {
                    partFilename = component
}
```

### CODE REVIEW

**Comment by dduan** [comment]
Thanks, @Minitour! Can you remove all the whitespace changes?

**Comment by Minitour** [comment]
I copied and pasted the raw code into Xcode and modified it there. I will create another pull request later on where the file will be modified directly rather than copying and pasting it.
Let me know @dduan if you want me to do that, unless you will commit the changes I mentioned above in the conversation yourself in a future update.

**Comment by JustHTTP** [comment]
I'll make this library work with Swift 3 in the future, yes :)

Daniel Duan

**Comment by dduan** [comment]
Updated master to work with Xcode GM. Thank you!

**Pull request closed without merging**
