### PR TITLE
Add Linux test runner

### PR DESCRIPTION
**Pull request by jey**
Made `swift test` work under Linux

### CODE REVIEW

**Comment by dduan** [comment]
Hi @jey, thank you very much for the contribution! I tried this [once](https://github.com/JustHTTP/Just/pull/79) and found that a lot of tests actually fail on Linux right now. Can you provide some stats on this before I merge your patch? How many of these tests are currently failing? Or, if you have left out some failing tests, which ones?

**Comment by dduan** [comment]
(also, I apologize for accidentally closing this PR, it wasn't intentional 😅)

**Comment by jey** [comment]
Hi @dduan. I've disabled the mimetype related tests on Linux because they cause a crash, and aside from that there's 4 tests that fail. I believe two are related to HTTP basic authentication and two are related to handling of redirects.

It looks like the NSURLSession implementation in Foundation is actively being worked on (see apple/swift-corelibs-foundation#970, apple/swift-corelibs-foundation#969, apple/swift-corelibs-foundation#968, apple/swift-corelibs-foundation#979. I'm hoping some of these bugs will get ironed out in the process, but I'll take another look at it after those larger changes have landed.

**Comment by gonzo-oin** [comment]
Does the library works on Linux ?

**Comment by JustHTTP** [comment]
As of now, multiple tests are failing on Linux due to bugs in the open source version of URLSession. But I know at least one of them is fixed. But I would not recommend using Just on Linux just yet.

Daniel Duan

**Comment by gonzo-oin** [comment]
Ok and thank you for the answer.
I'm looking for a http library like Just but that could work on Linux and didn't found one yet.

**Comment by JustHTTP** [comment]
Let's wait until Foundation is more mature. Enough work needs to happen at `URLSession` for linux for Just to "just work"

**Pull request closed without merging**
