### PR TITLE
Update to Swift 4

### PR DESCRIPTION
**Pull request by saagarjha**
Just a minor tweaks to get it compile in Swift 4 due to changes made by [SE-0154](https://github.com/apple/swift-evolution/blob/master/proposals/0154-dictionary-key-and-value-collections.md).

### CODE REVIEW

**Comment by saagarjha** [comment]
Hmm…it looks like the build is failing because `swift build --clean` was deprecated and removed. @dduan Would you like me to update [DistributionTests](https://github.com/dduan/DistributionTests)?

**Comment by dduan** [comment]
Hi @saagarjha thanks for the PR! Do you mind dropping the changes in `Just.xcodeproj/xcshareddata/xcschemes/Just.xcscheme` and `Just.xcodeproj/project.pbxproj`? We need to bump the language version number [here](https://github.com/JustHTTP/Just/blob/master/Supporting%20Files/xcconfigs/UniversalFramework_Base.xcconfig#L10).

**Comment by saagarjha** [comment]
Oh, I didn't notice the xcconfig. Let me fix it.

**Comment by saagarjha** [comment]
Thanks!

**Pull request merged**
