### PR TITLE
Use localizedStringForStatusCode instead of stored statusCodeDescriptions

### PR DESCRIPTION
**Pull request by mileswd**

### CODE REVIEW

**Comment by mileswd** [comment]
Many of the descriptions are the same, however they are a few changes:

I generated a list of differences using this snippet:
```swift
for i in 1...599 {
    if let statusCodeDescription = statusCodeDescriptions[i] {
      if statusCodeDescription != NSHTTPURLResponse.localizedStringForStatusCode(i) {
        println("\(i): \(statusCodeDescription) -> \(NSHTTPURLResponse.localizedStringForStatusCode(i))")
      }
    }
}
```
Which outputs the following:
```
102: processing -> informational
103: checkpoint -> informational
122: uri too long -> informational
200: ok -> no error
203: non authoritative info -> non-authoritative information
207: multi status -> success
208: already reported -> success
226: im used -> success
305: use proxy -> needs proxy
306: switch proxy -> redirected
307: temporary redirect -> temporarily redirected
308: permanent redirect -> redirected
406: not acceptable -> unacceptable
408: request timeout -> request timed out
410: gone -> no longer exists
413: request entity too large -> request too large
414: request uri too large -> requested URL too long
418: im a teapot -> client error
422: unprocessable entity -> client error
423: locked -> client error
424: failed dependency -> client error
425: unordered collection -> client error
426: upgrade required -> client error
428: precondition required -> client error
429: too many requests -> client error
431: header fields too large -> client error
444: no response -> client error
449: retry with -> client error
450: blocked by windows parental controls -> client error
451: unavailable for legal reasons -> client error
499: client closed request -> client error
501: not implemented -> unimplemented
504: gateway timeout -> gateway timed out
505: http version not supported -> unsupported version
506: variant also negotiates -> server error
507: insufficient storage -> server error
509: bandwidth limit exceeded -> server error
510: not extended -> server error
```

A quick summary of the differences:

Affected status code | Change made
----------------------------| -------------------
102, 103, 122, 207, 208, 226 | Clarified that no error actually occurred
200, 203, 305, 306, 307, 308, 406, 408, 410, 413, 414, 501, 504, 505 | Just a phrasing change
418, 422, 423, 424, 425, 426, 428, 429, 431, 444, 449, 450, 451, 499 | All changed to "client error", these are obviously client side and wouldn't (shouldn't) occur anyway - especially "blocked by windows parental controls" :wink:
506, 507, 509, 510 | Clarified that the error is not client-side, otherwise messages such as "insufficient storage" or "bandwidth limit exceeded" maybe misleading for a user

**Comment by dduan** [comment]
This is really tempting as it clears up the codebase by a lot. Unfortunately `localizedStringForStatusCode` is based on an [old RFC](http://www.ietf.org/rfc/rfc2616.txt) from 1999 that has since been [expanded](http://tools.ietf.org/html/rfc6585) in 2012. In other words, some of the codes descriptions that would be remove are part of the HTTP standard.

"blocked by windows parental controls" is a little conspicuous given the context (but Apple never said Swift is going to stay Apple-only 😛?)

Therefore this PR should be held until Apple updates `localizedStringForStatusCode`.

Thank you, @mileswd

**Comment by mileswd** [comment]
Ah, I understand. I wasn't aware of the internals surrounding the status codes, so thank you for explaining them :+1:

On an unrelated note, thank you so much for this library - it has made networking so much more clean and straightforward! :smile:

**Comment by dduan** [comment]
@mileswd I filed [rdar://21114301](http://www.openradar.me/radar?id=5752781671497728) so that your work doesn't amount to nothing 😉

**Comment by mileswd** [comment]
Once again, much appreciated - thanks! :blush:

**Pull request closed without merging**
