### PR TITLE
Keep url param type consistent

### PR DESCRIPTION
**Pull request by gtchance**

### CODE REVIEW

**Comment by dduan** [comment]
Ah oops. Thanks for catching this. Can we work out the context and squash all commits? ❤️

**Comment by gtchance** [comment]
Are you able to squash and merge?

**Comment by dduan** [comment]
I can squash and merge but there's a conflict it seems?

**Comment by gtchance** [comment]
That's strange. For me it says no conflicts. 🤔

**Comment by dduan** [comment]
Okay I can squash and merge. Can you edit the description to reflect the actual changes? It's out of date I think

**Pull request merged**
